dist: trusty
sudo: true
language: cpp

install:
      - if [[ -n "$CLANG_VERSION" ]]; then export CXX=clang++-$CLANG_VERSION CC=clang-$CLANG_VERSION; fi
      - if [[ -n "$GCC_VERSION" ]];   then export CXX=g++-$GCC_VERSION       CC=gcc-$GCC_VERSION;     fi

script:
    - mkdir build && cd build && cmake .. && make && ctest -V

matrix:
    include:
        - os: linux
          compiler: gcc
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                  packages:
                      - g++-6
          env: GCC_VERSION=6
        - os: linux
          compiler: clang
          addons:
              apt:
                  sources:
                      - ubuntu-toolchain-r-test
                      - llvm-toolchain-trusty-4.0
                  packages:
                      - clang-4.0
                      - g++-6
          env: CLANG_VERSION=4.0
        - os: osx
          osx_image: xcode8.2
          before_install:
              - brew update
              - brew install re2c
